"""Extract audited Java builder/map syntax; fail closed on unrecognised definitions."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SHA = '6e2a0a092fb794d7ea56fd83452869674f3ab1c7'
BASE = 'src/main/java/mods/flammpfeil/slashblade/'

def extract(source):
    def read(path):
        return (source / BASE / path).read_text()
    defaults = read('init/DefaultResources.java')
    resources = dict(re.findall(r'ResourceLocation\s+(\w+)\s*=\s*SlashBlade.prefix\("([^"]+)"\)', defaults))
    resources = {k: 'slashblade:' + v for k, v in resources.items()}
    resources['MotionLocation'] = 'slashblade:model/pa/player_motion.vmd'
    player_source = read('compat/playerAnim/PlayerAnimationOverrider.java')
    pattern = (r'map.put\(ComboStateRegistry\.(\w+)\.getId\(\),\s*new VmdAnimation\('
               r'(?:DefaultResources\.)?(\w+),\s*(\d+),\s*(\d+),\s*(true|false)\)'
               r'(\.setBlendLegs\(false\))?\);')
    player = [dict(combo=c, resource=resources[r], start=int(a), end=int(b), loop=l == 'true',
                   blend_legs=not bool(legs)) for c,r,a,b,l,legs in re.findall(pattern, player_source)]
    assert len(player) == player_source.count('map.put('), 'Unhandled player mapping'
    combo_source = read('registry/ComboStateRegistry.java')
    builder = read('registry/combo/ComboState.java')
    default_motion = re.search(r'this.motionLoc = DefaultResources\.(\w+);', builder)[1]
    declarations = list(re.finditer(r'public static final RegistryObject<ComboState>\s+(\w+)\s*=\s*COMBO_STATE.register\s*\(\s*"([^"]+)"', combo_source))
    blade = []
    for i, m in enumerate(declarations):
        block = combo_source[m.end():declarations[i+1].start() if i+1<len(declarations) else len(combo_source)]
        frames = re.search(r'\.startAndEnd\(\s*(\d+)\s*,\s*(\d+)\s*\)',block)
        assert frames, m[1]
        motion = re.search(r'\.motionLoc\(DefaultResources\.(\w+)\)',block)
        speed = re.search(r'\.speed\(([\d.]+)[fF]?\)',block)
        timeout = re.search(r'\.timeout\((\d+)\)',block)
        blade.append(dict(combo=m[1], id='slashblade:'+m[2], start=int(frames[1]),end=int(frames[2]),
            resource=resources[motion[1] if motion else default_motion], explicit_resource=bool(motion),
            speed=float(speed[1]) if speed else 1.0, timeout_ms=int(timeout[1]) if timeout else 0,
            loop='.loop()' in block, source_line=combo_source[:m.start()].count('\n')+1))
    assert len(blade) == combo_source.count('COMBO_STATE.register'), 'Unhandled combo'
    for kind, rows, src in [('player',player,player_source),('blade',blade,combo_source)]:
        obj=dict(repository='0999312/SlashBlade_Resharped',commit=SHA,minecraft='1.20.1',version='1.9.65',
                 source_sha256=hashlib.sha256(src.encode()).hexdigest(), entries=rows)
        (ROOT/'data').mkdir(exist_ok=True)
        (ROOT/'data'/f'resharped_{kind}_frame_map.json').write_text(json.dumps(obj,indent=2)+'\n')
        out=ROOT/'docs/mapping';out.mkdir(parents=True,exist_ok=True)
        text=f'# Resharped {kind} frame map\n\nGenerated by `scripts/extract_frame_maps.py`.\n\nCommit: `{SHA}`; Minecraft 1.20.1; Resharped 1.9.65.\n\n'
        text+='| Combo | Resource | Frames | Loop |\n|---|---|---|---|\n'
        text+=''.join(f'| {r["combo"]} | `{r["resource"]}` | {r["start"]}–{r["end"]} | {r["loop"]} |\n' for r in rows)
        text+='\nRanges overlap intentionally. A shared frame cannot have two different poses. '
        text+='Player callbacks do not exist for every blade state. Blade speed metadata does not imply player playback is retimed.\n'
        (out/f'resharped-{kind}-frame-map.md').write_text(text)
    print(f'Extracted {len(player)} player and {len(blade)} blade mappings')

if __name__ == '__main__':
    ap=argparse.ArgumentParser();ap.add_argument('source',type=Path)
    extract(ap.parse_args().source)
